<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>管理员登陆</title>
        <style type="text/css">
            <!--
            body {
                margin: 0px;
                padding: 0px;
                word-break : normal;
                word-wrap : break-word;
                font-family: "????", Verdana, Arial, Helvetica, sans-serif;
                font-size: 12px;
                background-color: #F5F5F5;
            }
            form {
                margin: 0px;
                padding: 0px
            }
            input {
                border: 1px solid #CCCCCC;
                background-color: #FFFFFF;
                padding: 2px;
                height: 16px
            }
            .submit {
                height: 22px;
                background-color: #CCCCCC
            }
            .radio {
                border: 0px
            }
            a {
                color: #1C5F82;
                text-decoration: none;
            }
            a:hover {
                text-decoration: underline;
            }
            -->
        </style>
    </head>

    <body bgcolor="#F5F5F5" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
        <table width="100%" border="0" cellspacing="0" cellpadding="3">
            <tr>
                <td width="150" bgcolor="#4B5F78">&nbsp;</td>
                <td bgcolor="#4B5F78">&nbsp;</td>
                <td width="350" bgcolor="#4B5F78" style="color: #FFFFFF">
                </td>
            </tr>
            <tr>
                <td colspan="3" bgcolor="#D4DCE4">&nbsp;</td>
            </tr>
        </table>
        <br /><script language="javascript" type="text/javascript">
            function PasteSn()
            {
                if (!window.clipboardData)
                    return;
                var CopySn = clipboardData.getData("Text");
                if (CopySn.length == 36)
                {
                    document.all("serial")[0].value = CopySn.substring(0, 7);
                    document.all("serial")[1].value = CopySn.substring(9, 13);
                    document.all("serial")[2].value = CopySn.substring(14, 18);
                    document.all("serial")[3].value = CopySn.substring(19, 23);
                    document.all("serial")[4].value = CopySn.substring(24, 36);
                    document.all("serial")[4].focus();
                }
            }

            function Sn_onkeyup(num)
            {
                var this_sn = document.all("serial")[num];
                //this_sn.value = this_sn.value.toUpperCase();
                this_sn.value = this_sn.value.replace("\-", "");
                //alert(this_sn.value);
                var next_sn = document.all("serial")[num + 1]
                if (num == 0) {
                    if (this_sn.value.length >= 8)
                        next_sn.focus()
                }
                if (num == 1) {
                    if (this_sn.value.length >= 4)
                        next_sn.focus()
                }
                if (num == 2) {
                    if (this_sn.value.length >= 4)
                        next_sn.focus()
                }
                if (num == 3) {
                    if (this_sn.value.length >= 4)
                        next_sn.focus()
                }
                //if (! this_sn.value.match(/^[0-9a-zA-Z]$/)) alert('提示：密码不合格');
            }
        </script>
        <div style="text-align:center;"><?php echo $this->message; ?> </div>
        <form action="<?php echo $this->url(array('action' => 'index', 'controller' => 'login', 'module' => 'admin')); ?>" method="post" name="admin" target="_top" id="admin">
            <table width="600" border="0" align="center" cellpadding="2" cellspacing="0">
                <tr>
                    <td>ＩＤ：
                        <input name="<?php echo $this->form->getId()->getName(); ?>" type="text" id="id" size="12" value="" maxlength="12" onkeyup="if (event.keyCode != 37 && event.keyCode != 39)
                                    value = value.replace(/\D/g, '');" onblur="if (this.value == '')
                                                this.value = '0'" style="width: 100px;" /></td>
                    <td width="400">&nbsp;</td>
                </tr>
                <tr>
                    <td>用户名：
                        <input name="<?php echo $this->form->getName()->getName(); ?>" type="text" id="id" size="12" value="" maxlength="12" onkeyup="if (event.keyCode != 37 && event.keyCode != 39)
                                    value = value.replace(/\D/g, '');" onblur="if (this.value == '')
                                                this.value = ''" style="width: 100px;" /></td>
                    <td width="400" >&nbsp;</td>
                </tr>
                <tr>
                    <td>密 码：
                        <input name="<?php echo $this->form->getPass()->getName(); ?>" type="password" id="password" size="12" style="width: 100px;" value="" /></td>
                    <td width="400">&nbsp;</td>
                </tr>
                <tr>
                    <td>验证码：
                        <input name="captcha" type="text" id="captcha" size="12" style="width: 100px;" value="" /><img src="/captcha/index/" onclick="this.src = '/captcha/index?rand=' + Math.random();" /></td>
                    <td width="400">&nbsp;</td>
                </tr>
                <tr>
                    <td  colspan="2"></td>
                </tr>
                <tr>
                    <td colspan="2" align="center"><input type="submit" class="submit" value="登陆" /></td>
                </tr>
            </table>

        </form>
    </body>
</html>
